name: Keep Render App Awake

on:
  schedule:
    # Runs every 14 minutes
    - cron: "*/14 * * * *"
  workflow_dispatch: # allows manual trigger too

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render App
        run: |
          curl -s https://gardentracker.onrender.com > /dev/null 2>&1
